import "./globals.css"
import "react-toastify/dist/ReactToastify.css"
import "tailwindcss/tailwind.css"

import type { Metadata } from "next"
import MaterialProvider from "@/components/MaterialProvider"
import { ToastContainer } from "react-toastify"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <MaterialProvider>{children}</MaterialProvider>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
      </body>
    </html>
  )
}
